import { z } from 'zod';
export const cameraAngles=['down-the-line','face-on'] as const; export const clubs=['Driver','Fairway wood','Hybrid','Long iron','Mid iron','Short iron','Wedge','Other'] as const; export const shotResults=['Straight','Pull','Push','Fade','Slice','Draw','Hook','Fat','Thin','Topped','Unknown'] as const;
export const envSchema=z.object({NEXT_PUBLIC_APP_URL:z.string().url().optional().or(z.literal('')),NEXT_PUBLIC_SUPABASE_URL:z.string().url().optional().or(z.literal('')),NEXT_PUBLIC_SUPABASE_ANON_KEY:z.string().optional(),SUPABASE_SERVICE_ROLE_KEY:z.string().optional(),OPENAI_API_KEY:z.string().optional(),OPENAI_VISION_MODEL:z.string().default('gpt-4.1-mini'),MAX_VIDEO_SIZE_MB:z.coerce.number().default(100),MAX_VIDEO_DURATION_SECONDS:z.coerce.number().default(30),MAX_ANALYSIS_FRAMES:z.coerce.number().min(3).max(12).default(9),DEMO_MODE:z.coerce.boolean().default(true)});
export const appEnv=envSchema.parse(process.env);
export const uploadSchema=z.object({cameraAngle:z.enum(cameraAngles),club:z.enum(clubs),shotResult:z.enum(shotResults).default('Unknown'),ballFlight:z.string().max(120).optional(),notes:z.string().max(1000).optional()});
export const frameSchema=z.object({id:z.string(),label:z.string(),stage:z.string(),imageUrl:z.string(),time:z.number()});
const confidence=z.enum(['high','medium','low']);
export const swingAnalysisSchema=z.object({overallSummary:z.string(),strongestFeature:z.object({title:z.string(),explanation:z.string(),confidence}),primaryPriority:z.object({title:z.string(),visibleEvidence:z.string(),likelyEffect:z.string(),confidence}),secondaryPriority:z.object({title:z.string(),visibleEvidence:z.string(),likelyEffect:z.string(),confidence}).optional(),stages:z.array(z.object({stage:z.enum(['setup','takeaway','backswing','top','transition','delivery','impact','followThrough']),observation:z.string(),status:z.enum(['positive','attention','neutral','notAssessable']),confidence,relatedFrameIds:z.array(z.string())})),primaryFeel:z.object({cue:z.string(),explanation:z.string()}),drills:z.array(z.object({name:z.string(),purpose:z.string(),instructions:z.array(z.string()),repetitions:z.string(),safetyNote:z.string().optional()})).max(2),nextSession:z.object({practiceFocus:z.string(),filmingInstruction:z.string(),successIndicator:z.string()}),limitations:z.array(z.string())});
export type SwingAnalysis=z.infer<typeof swingAnalysisSchema>; export type Frame=z.infer<typeof frameSchema>;
export function validateVideo(file:{size:number;type:string;name:string}, maxMb=appEnv.MAX_VIDEO_SIZE_MB){const ok=['video/mp4','video/quicktime','video/mov','video/webm','video/x-m4v']; const ext=/\.(mp4|mov|m4v|webm)$/i.test(file.name); if(file.size>maxMb*1024*1024)return `Video must be ${maxMb} MB or smaller.`; if(!ok.includes(file.type)&&!ext)return 'Upload an MP4, MOV, M4V or WebM phone video.'; return null;}
